### ISSUE TITLE
/home/p0f-logs/socket

### ISSUE THREAD

**Issue by leakeung** [ValdikSS/p0f-mtu-script#1]
Hello, can you put the/home/p0f - logs/above the socket on the socket open source? Thank you for

**Comment by ValdikSS** [comment]
Excuse me? I don't understand.

**Comment by leakeung** [comment]
Hello, I am Chinese, English is not very good!
In PHP, this line of code, in the index.
The exec ("/home/p0f - mtu/tools/p0f - client/home/p0f - logs/socket ". $_SERVER [' REMOTE_ADDR], $pof_output);
The first argument why this happen

**Comment by ValdikSS** [comment]
It executes p0f-client with socket path. p0f-client is a client you can find in "tools" folder of p0f.

**Comment by leakeung** [comment]
I have seen https://github.com/ValdikSS/p0f-mtu, tried to install, but failed in the end.

**Comment by ValdikSS** [comment]
To build client, you should run "make" in p0f "tools" folder
https://github.com/ValdikSS/p0f-mtu/tree/master/tools

**Comment by leakeung** [comment]
Enter the tools folder, and then run "make"?

**Comment by ValdikSS** [comment]
Yes.

**Comment by leakeung** [comment]
After the make?

**Comment by ValdikSS** [comment]
After make you can run client.

    ./p0f-client

**Comment by leakeung** [comment]
Can directly enter the command window. / p0f - client? So you can perform?
Finally in the PHP can also use the exec ("/home/p0f - mtu/tools/p0f - client/home/p0f - logs/socket ". $_SERVER [' REMOTE_ADDR], $pof_output); ??

**Comment by leakeung** [comment]
Hello, after I make, and then execute"./p0f-client /home/p0f-logs/socket"  the following information:
[-] SYSTEM ERROR : Can't connect to API socket.
        Location : main(), p0f-client.c:128
      OS message : No such file or directory

**Comment by ValdikSS** [comment]
You should run p0f first, then use the client.

**Comment by leakeung** [comment]
In p0f - mtu folder one build.Sh need to perform?

**Comment by ValdikSS** [comment]
Yes

**Comment by leakeung** [comment]
run p0f first?In p0f-mtu folder, also need to make first?

**Comment by ValdikSS** [comment]
Please read this

http://lcamtuf.coredump.cx/p0f3/README

**Comment by leakeung** [comment]
I'm sorry, I ability is limited.
run . / p0f is working,
but cd tools  to run "./p0f-client xx  xx " is failure. 
notice: SYSTEM ERROR : Can't connect to API socket.

**Comment by ValdikSS** [comment]
```
./p0f -s socket
./tools/p0f-client ./socket
```

**Comment by leakeung** [comment]
run "./tools/p0f-client ./socket IP" no response? I input the wrong? So does change the IP.

**Comment by ValdikSS** [comment]
You should run p0f as root in one window and client in another. p0f should be running when you use client.

**Comment by leakeung** [comment]
Thank you, must keep p0f background continues to run. When users request was then extracted data in the cache

**Comment by ValdikSS** [comment]
Yes.
