### ISSUE TITLE
result is different

### ISSUE THREAD

**Issue by lucas1** [ValdikSS/p0f-mtu-script#3]
**My server:**
First seen    = 2017/03/30 01:53:30
Last update   = 2017/03/30 01:53:38
Total flows   = 8
Detected OS   = Linux 2.2.x-3.x (no timestamps) [generic]
HTTP software = ???
MTU           = 1500
Network link  = Ethernet or modem
Language      = Portuguese
Distance      = 10
IP sharing    = 2017/03/30 01:53:37
Sys change    = 2017/03/30 01:53:39

PTR test      = Probably home user
Fingerprint and OS match. No proxy detected (this test does not include headers detection).
No OpenVPN detected.
Getting your NTLM hash…

**Your site http://witch.valdikss.org.ru/:**
First seen    = 2017/03/30 02:10:05
Last update   = 2017/03/30 02:41:17
Total flows   = 4
Detected OS   = Linux 3.11 and newer
HTTP software = Chrome 51.x or newer (ID seems legit)
MTU           = 1408
Network link  = OpenVPN UDP bs64 SHA1 lzo
Language      = Portuguese
Distance      = 14
Uptime        = 10 days 3 hrs 36 min (modulo 198 days)

PTR test      = Probably home user
Fingerprint and OS match. No proxy detected (this test does not include headers detection).
OpenVPN detected. Block size is 64 bytes long (probably Blowfish), MAC is SHA1, LZO compression enabled.
No NTLM hash is leaked. Try to manually copy&paste
file://witch.valdikss.org.ru/a to the address bar (Windows with IE/Edge/Chrome) or
\\witch.valdikss.org.ru\a (Windows with Firefox).

**Comment by ValdikSS** [comment]
You need to use p0f-mtu, not the original one.
https://github.com/ValdikSS/p0f-mtu

**Comment by lucas1** [comment]
Ok, I will open issue in original. Thanks.
