### ISSUE TITLE
Scripts p0f-client and p0f-socket are missing

### ISSUE THREAD

**Issue by sedimentation-fault** [ValdikSS/p0f-mtu-script#4]
As I see read the code of index.php, it tries to execute two local scripts:

- /opt/p0f-mtu/tools/p0f-client
- /opt/p0f-mtu/p0f-socket 

in this line:

`exec("/opt/p0f-mtu/tools/p0f-client /opt/p0f-mtu/p0f-socket ".$_SERVER['REMOTE_ADDR'], $pof_output);`

The scripts are missing from the package. Can you please add them? It's where the whole work is done, right? ;-)

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/p0f-mtu
