### ISSUE TITLE
Problem with runing script

### ISSUE THREAD

**Issue by walruzperil** [ValdikSS/p0f-mtu-script#5]
Hello, i install p0f. Then i tried open your script in web. I see nothing about OS. Only PTR           = r-239-60-62-5.consumer-pool.prcdn.net ... in index.php i change to 
exec("/opt/p0f-3.09b/tools/p0f-client /opt/p0f-3.09b/p0f-socket ".$_SERVER['REMOTE_ADDR'], $pof_output);
that actual folder where p0f located... Can you halp me please...

**Comment by ValdikSS** [comment]
p0f is not running, client is not working, or something else. Check manually with p0f-client if it works and outputs expected values. If it does work, check why it doesn't work with php. Maybe you have safe_mode enabled or other restrictions.
