### ISSUE TITLE
issue back nginx intend of chrome

### ISSUE THREAD

**Issue by turbo-4g** [ValdikSS/p0f-mtu-script#6]
hello whene we try the script is back 
HTTP software | nginx 1.x (ID is fake)
Network link | DSL
and in http://witch.valdikss.org.ru/
HTTP software = Chrome 60.x or newer (ID seems legit)
MTU           = 1492
Network link  = PPPoE

any fix please ?

**Comment by ValdikSS** [comment]
This is not an issue.
